### ISSUE TITLE
streaming support

### ISSUE THREAD

**Issue by tanner0101** [vapor/multipart-kit#33]
Support for parsing streaming bodies could greatly reduce memory usage for decoding multipart forms. This API would need to be asynchronous, so it could not be used with Codable. However, it could allow you to access multipart parts as they become available, and even stream large parts (like files) by chunk. All while using very little memory if done correctly.

**Comment by Magiguigui** [comment]
Is this still relevant ?
I'm trying to achieve this by using : https://github.com/mcritz/VaporUploads, but I ended as conclusion that I can't decode a form as same time as i'm streaming the body (because it's streaming the entire form and not only files...)

**Comment by tanner0101** [comment]
Vapor 4's multipart parser supports streaming: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Multipart/MultipartParser.swift

This package is deprecated for the time being. Eventually the upgraded multipart code from Vapor 4 will be brought back here.

**Comment by joshuawright11** [comment]
@siemensikkema is streaming possible right now?

If so, would the correct way to do so be to call `.execute(chunk)` with each incoming chunk on the `MultipartProcessor`?

**Comment by siemensikkema** [comment]
@joshuawright11 Yes, that's the idea! I have yet to try out streaming in a real project but the `MultipartParser` is built with that in mind.
