### ISSUE TITLE
Add null-termination to strncpy call

### ISSUE THREAD

**Issue by KevinHock** [vapor/multipart-kit#41]
It seems there is a bug of this nature https://stackoverflow.com/questions/1176737/strncpy-and-using-sizeof-to-copy-maximum-characters

Located here https://github.com/francoiscolas/multipart-parser/blob/b0bc117dba58a03bb99f46bd8d03a720bb802e7b/multipartparser.c#L96-L97

It seems it is fixable by adding `- 1` e.g. `strncpy(parser->boundary, boundary, sizeof(parser->boundary) - 1);`, because of the preceding `memset(parser, 0, sizeof(*parser));` call.

Apologies in advanced if this is a false-positive.

**Comment by tanner0101** [comment]
@KevinHock do you have a failing test case you could share here to ensure we don't have a regression?

**Comment by KevinHock** [comment]
Unfortunately I don't have a failing test case, but initiating a `MultipartParser` with a boundary 70 or greater should trigger it, e.g. https://github.com/vapor/multipart-kit/blob/a941d7a1d685c83df09077f6190808ff2a7f4dce/Tests/MultipartKitTests/MultipartKitTests.swift#L36 but longer.

(Code path to the C code from Swift being https://github.com/vapor/multipart-kit/blob/a941d7a1d685c83df09077f6190808ff2a7f4dce/Sources/MultipartKit/MultipartParser.swift#L15-L38)
