### ISSUE TITLE
Decoding optional type cause error

### ISSUE THREAD

**Issue by emilwojtaszek** [vapor/multipart-kit#68]
### Describe the bug

This one works:
```swift
let foo = try FormDataDecoder().decode(Foo.self, from: data, boundary: "12345")
```

this one doesn't 
```swift
let foo = try FormDataDecoder().decode(Foo?.self, from: data, boundary: "12345")
```

Error:
```
caught error: "typeMismatch(MultipartKit.OrderedDictionary<Swift.String, MultipartKit.MultipartFormData>, Swift.DecodingError.Context(codingPath: [], debugDescription: "expected single value but encountered dictionary", underlyingError: nil))"
```

### To Reproduce

You can adjust `func testFormDataDecoderW3()` to see this behaviour 

### Expected behavior

Content should be decoded no matter if type is Foo.self or Foo?.self 

### Environment

Tested od `mian` branch

**Comment by siemensikkema** [comment]
@emilwojtaszek this appears to happen only when the top-level object is an optional. I'll need to look into it further. Thanks for reporting!
