### ISSUE TITLE
Un-vendor the `swift-collections` implementation

### ISSUE THREAD

**Issue by gwynne** [vapor/multipart-kit#82]
`multipart-kit` currently contains a somewhat outdated version of `OrderedSet` and `OrderedDictionary` taken from the then-current pre-release version of `swift-collections`; this vendored implementation should be replaced with a dependency on `swift-collections` 1.x.

cc @siemensikkema

**Comment by ahmdyasser** [comment]
Should this PR include deleting the current `OrderedSet` implementation files?

**Comment by gwynne** [comment]
That's the intention, yes.

**Comment by ahmdyasser** [comment]
> That's the intention, yes.

done! checkout my PR

**Comment by ahmdyasser** [comment]
Hi @gwynne! I cannot assign myself to any of the issues in the board. I think I first need to be a member? is it possible to add me to "members"?
<img width="325" alt="image" src="https://user-images.githubusercontent.com/42544598/166462307-d00c7434-5766-46c4-9a76-ca7e35de46aa.png">
