### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by varungakhar** [vapor/multipart-kit#86]
### Describe the bug

OS - Ubuntu 20.04
When i try to upload the file more than 65 kb , server hangs sometimes . I got the error from nginx 
request timed out. i have set proxy_read_time set to 10s . 

I have also tried this in local setup (mac mini M1). Its takes 6-7 seconds to upload the file. the issue seems to exist in 4.0.0 + version

When i tried to upload file with cmultiparser (4.0.0) . Server never hangs and response time is also fast. In local setup it takes milliseconds 

### To Reproduce

1. Upload the file larger than 65kb you will see the lag . You can try in local setup too 

I think issue exist in this function
https://github.com/vapor/multipart-kit/blob/0d55c35e788451ee27222783c7d363cb88092fab/Sources/MultipartKit/MultipartParser.swift#L76

### Expected behavior

It should you work like cmultiparser

### Environment

* Vapor Framework version: 4.67.0
* Vapor Toolbox version:
* OS version: Ubuntu 20.04

* Vapor Framework version: 4.67.0
* Vapor Toolbox version:
* OS version: Mac mini M1 ( Ventura 13.0 (22A380))

**Comment by 0xTim** [comment]
Are you running when you've compiled in release mode rather than debug?

**Comment by varungakhar** [comment]
It is happening only in debug mode

supervisor cmd 
command=/home/ubuntu/thirdeyeserver/.build/x86_64-unknown-linux-gnu/debug/Run serve

**Comment by 0xTim** [comment]
That's expected, it's unfortunately a Swift issue and not much we can do about it. We recommend running in release mode when you're doing actual performance testing. I'll close this but feel free to reopen if you want to
