### ISSUE TITLE
Can change Content-Disposition string？

### ISSUE THREAD

**Issue by YelCode** [vapor/multipart-kit#98]
### Describe the issue

Can change Content-Disposition string？

### Vapor version

4.6.0

### Operating system and version

Mac 

### Swift version

5.9.0

### Steps to reproduce

1.upload file
2.then the file header Content-Disposition: form-data; filename="1721182375.png"; name="file"
now I want Content-Disposition: form-data; name="file"; filename="1721182375.png"
can I change name and filename？
 

### Outcome

upload result  header Content-Disposition: form-data; filename="1721182375.png"; name="file"
I want Content-Disposition: form-data; name="file"; filename="1721182375.png"

### Additional notes

M2 Mac

**Comment by 0xTim** [comment]
You can manually override the header in a request with `request.headers.contentDisposition = ...`. There is [nothing in the spec](https://www.ietf.org/rfc/rfc2183.txt) that requires a specific order so overriding it is not something Vapor supports
