### ISSUE TITLE
Inconstancy between the ReadMe and the Package.swift, is iOS supported? 

### ISSUE THREAD

**Issue by TMinYou** [vapor/multipart-kit#99]
### Describe the issue

The read me doesn't list iOS as a supported platform, yet the Package.swift file seems to include it, which is correct

### Vapor version

N/A

### Operating system and version

N/A

### Swift version

N/A

### Steps to reproduce

Take a look at the ReadMe file and the Package.swift file. 
Note that under [supported platforms](https://github.com/vapor/multipart-kit?tab=readme-ov-file#supported-platforms) iOS is not listed yet in the Package.swift file it is listed under platforms 
```  name: "multipart-kit",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
       ...
```
I am interested in using this on iOS and would like to confirm that it is indeed supported. If so I'm more than happy to fix the ReadMe. 

thanks

PS Sorry if creating a bug isn't the correct work flow for this case

### Outcome

N/A

### Additional notes

N/A

**Comment by 0xTim** [comment]
@TMinYou we provide experimental support for iOS for this. Note that we don't do any testing on iOS so can't guarantee it definitely works, but I can't see any reason why it wouldn't. Feel free to reopen if you hit issues, or create new issues
